name: Deploy New Version (PROD)

on:
  push:
    tags:
      - "v1.*.**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Create SSH key file
        run: echo "${{ secrets.SSH_KEY }}" > id_rsa && chmod 600 id_rsa

      - name: Prepare deploy-script
        run: |
          cat > deploy-script.sh <<EOF
          cd ${{ secrets.PROJECT_FOLDER }}
          php artisan down
          git reset --hard
          git clean -df
          git fetch --all --tags
          git checkout tags/${{ env.RELEASE_VERSION }} -b ${{ env.RELEASE_VERSION }}-branch
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan optimize:clear
          php artisan migrate --force
          php artisan optimize
          php artisan route:clear
          npm install && npm run dev
          php artisan up
          EOF
      - name: Run deploy-script on server
        run: >
          ssh "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}"
          -o StrictHostKeyChecking=accept-new
          -i id_rsa
          "bash -s"
          < deploy-script.sh
