name: Run Laravel Tests

on:
  pull_request:
    branches: [main]

env:
  APP_ENV: testing

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: laravel

    steps:
      - uses: actions/checkout@v3

      - name: PHP Version
        run: php -v

      - name: Check PHP platform requirements
        run: composer check-platform-reqs

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: |
          php -v
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}" 
          composer install -n --prefer-dist

      - name: Copy .env
        run: |
          cp .env.example .env
          
      - name: Prepare Laravel Application
        run: |
          php artisan key:generate --env=testing
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Run yarn
        run: yarn && yarn dev

      - name: Run tests
        run: php artisan test
        env: 
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: laravel
          DB_DATABASE: laravel

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
